name: MSBuild and Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}

    - name: Compress x64 Output
      run: Compress-Archive -Path .\x64\Release\ -DestinationPath Release-x64.zip
      shell: pwsh

    - name: Compress x86 Output
      run: Compress-Archive -Path .\Release\ -DestinationPath Release-x86.zip
      shell: pwsh

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: |
          Release-x64.zip
          Release-x86.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
